# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e0f39d67232f467376f247ba93524997715a3b8d3f0d78d47d9b77aa4147757c6f13033dda76eb19fde31b0fa5fba6c906c457b79872322081941374e805e22

test:
  secret_key_base: 409e3b75374836128081ba1b4976b7d3e6fd39e4782d4af6cbfd23fd581fe7024a4f5c4adb96b820b5dc15ebb8317082bcbe497a8b15b28391cf656963dbb6b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
